version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.microsoft.sqlserver:mssql-jdbc
    versions:
    - "> 6.4.0.jre8"
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
  - dependency-name: net.sf.jt400:jt400
    versions:
    - "10.5"
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
